const $=s=>document.querySelector(s);let cached=[];
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok) throw new Error(j.error||'Request failed');return j}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function date(s){return s?new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—'}
function renderChart(points){const el=$('#traffic-chart');if(!points.length){el.innerHTML='<div class="empty-state">No traffic recorded yet.</div>';return}const max=Math.max(...points.map(([,v])=>v),1);el.innerHTML=points.map(([d,v])=>`<div class="chart-column" title="${esc(d)} · ${v} views"><i style="height:${Math.max(5,v/max*100)}%"></i><span>${new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div>`).join('')}
function render(data){$('#m-views').textContent=data.metrics.views.toLocaleString();$('#m-unique').textContent=data.metrics.unique_visitors.toLocaleString();$('#m-inquiries').textContent=data.metrics.inquiries.toLocaleString();$('#m-conversion').textContent=(data.metrics.conversion*100).toFixed(1)+'%';renderChart(data.views_by_day);$('#page-list').innerHTML=data.views_by_page.length?data.views_by_page.slice(0,8).map(([p,v],i)=>`<div><span><b>${String(i+1).padStart(2,'0')}</b>${esc(p)}</span><strong>${v}</strong></div>`).join(''):'<div class="empty-state">No page views yet.</div>';cached=data.inquiries;const body=$('#inquiries-body');body.innerHTML=data.inquiries.map(i=>`<tr><td><strong>${esc(i.name)}</strong><small>${i.guests} guest${i.guests===1?'':'s'}</small></td><td>${esc(date(i.arrival))}<small>to ${esc(date(i.departure))}</small></td><td><a href="mailto:${encodeURIComponent(i.email)}">${esc(i.email)}</a>${i.phone?`<a href="tel:${esc(i.phone)}">${esc(i.phone)}</a>`:''}</td><td class="message-cell">${esc(i.message||'—')}</td><td>${esc(date(i.created_at))}</td><td><select class="status-select" data-id="${esc(i.id)}"><option value="new" ${i.status==='new'?'selected':''}>New</option><option value="contacted" ${i.status==='contacted'?'selected':''}>Contacted</option><option value="booked" ${i.status==='booked'?'selected':''}>Booked</option><option value="closed" ${i.status==='closed'?'selected':''}>Closed</option></select></td></tr>`).join('');$('#empty-inquiries').hidden=!!data.inquiries.length;body.querySelectorAll('.status-select').forEach(s=>s.addEventListener('change',async()=>{try{await api('/api/dashboard',{method:'PATCH',body:JSON.stringify({id:s.dataset.id,status:s.value})})}catch(e){alert(e.message)}}))}
async function load(){try{const data=await api('/api/dashboard?days='+$('#period').value);render(data)}catch(e){if(/Unauthorized/i.test(e.message)){showLogin()}else alert(e.message)}}
function showLogin(){ $('#dashboard-view').hidden=true;$('#login-view').hidden=false }
function showDashboard(){ $('#login-view').hidden=true;$('#dashboard-view').hidden=false;load() }
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const note=$('#login-note');note.textContent='Checking…';try{await api('/api/auth',{method:'POST',body:JSON.stringify({password:$('#owner-password').value})});showDashboard()}catch(err){note.textContent=err.message}});$('#period').addEventListener('change',load);$('#refresh').addEventListener('click',load);$('#logout').addEventListener('click',async()=>{await api('/api/auth',{method:'DELETE'});showLogin()});$('#export-csv').addEventListener('click',()=>{const fields=['name','email','phone','arrival','departure','guests','message','status','created_at'];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[fields.join(','),...cached.map(r=>fields.map(f=>q(r[f])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='lgvc-inquiries.csv';a.click();URL.revokeObjectURL(a.href)});
api('/api/auth').then(x=>x.authenticated?showDashboard():showLogin()).catch(showLogin);
