-- Run this once in the Supabase SQL editor for the project used by La Galerie du Vieux Carré.
create extension if not exists pgcrypto;
create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  check_in date not null,
  check_out date not null,
  guests integer not null,
  message text,
  status text not null default 'new' check (status in ('new','contacted','closed'))
);
create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null,
  session_id text,
  referrer text
);
create index if not exists inquiries_created_at_idx on public.inquiries(created_at desc);
create index if not exists site_events_created_at_idx on public.site_events(created_at desc);
-- The site uses the service-role key only inside Vercel serverless functions. Never expose it in browser code.
